### ISSUE TITLE
Get a error when count of tabbar from 1 to 2

### ISSUE THREAD

**Issue by huang12zheng** [imaNNeoFighT/circular_bottom_navigation#20]
tabs.length change from 1 to 2, it is getting a error with follow code.
```dart
CircularBottomNavigation(
              tabs.map2TabItem(),
              controller: _navigationController,
              barHeight: bottomNavBarHeight,
              selectedCallback: (int index) {
                controller.jumpToPage(index);
              },
            )
```
* PS:
I just solve problem by as follow:

```dart
Align(
          alignment: Alignment.bottomCenter,
          child: (tabs?.length??0) == 0 ? Container() : 
          StatefulBuilder(
            key: ValueKey(tabs.length),
            builder: (BuildContext context, setState) => CircularBottomNavigation(
              tabs.map2TabItem(),
              controller: _navigationController,
              barHeight: bottomNavBarHeight,
              selectedCallback: (int index) {
                controller.jumpToPage(index);
              },
            )
          ),
        )
```

---------
* debug info
```dart
(_itemsSelectedState[pos] * ((widget.barHeight / 2) + widget.circleStrokeWidth)),
```

```bash
The following RangeError was thrown building CircularBottomNavigation(dirty, dependencies: [MediaQuery], state: _CircularBottomNavigationState#b3126(tickers: tracking 1 ticker)):
RangeError (index): Invalid value: Only valid value is 0: 1

The relevant error-causing widget was
    CircularBottomNavigation 
lib/…/tabview/tabview_scaffold.dart:55
When the exception was thrown, this was the stack
#0      List.[]  (dart:core-patch/growable_array.dart:149:60)
#1      _CircularBottomNavigationState.build.<anonymous closure> 
package:circular_bottom_navigation/circular_bottom_navigation.dart:196
#2      ListMapView.forEach  (dart:_internal/list.dart:244:8)
#3      _CircularBottomNavigationState.build 
package:circular_bottom_navigation/circular_bottom_navigation.dart:178
#4      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4069
...
```

**Comment by huang12zheng** [comment]
it maybe need a Key or use didUpdateWidget

**Comment by huang12zheng** [comment]
close with no reply
